### ISSUE TITLE
Error when folder have children

### ISSUE THREAD

**Issue by Tertiumnon** [Tertiumnon/json-all-to-one#7]

**Comment by Tertiumnon** [comment]
not reproduced

**Comment by Tertiumnon** [comment]
`undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at D:\Users\vitba\AppData\Roaming\npm\node_modules\json-all-to-one\json-all-to-one.js:50:27
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:47:12)`
